CREATE TABLE users (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(100) NOT NULL,
    role varchar(100) NOT NULL,
    password varchar NOT NULL
);

INSERT INTO users (username, role, password) VALUES ('admin', 'ADMIN', '1234');
INSERT INTO users (username, role, password) VALUES ('user', 'USER', '$2a$12$WDisZbYDFz5JNhj685Z34uglDeF4iDfqBswR3zOU7SIQGrHeFto0W');